siteTitle = "Textkrieg"
siteDescr = "awkwardness as a service"
siteAuthor = "Ada Blitz"

siteTwitterUrl = "https://twitter.com/bangpowwww"
siteEmailUrl = "mail-to:kontakt@textkrieg.de"

googleAnalyticsId = ""

linkPrefix = "/gatsby-starter-lumen"
